### ISSUE TITLE
Is it possible to make this work with CRNA?

### ISSUE THREAD

**Issue by rodolfofranco** [line64/react-native-checkout-mercadopago#14]
Hi, i have read the documentation and i can see that the steps are meant for developers working with `react-native cli` but nothing about Expo and CRNA. So my question is, can this work with a project done with CRNA? If so, can someone explain ? I'll provide code if necessary.

**Comment by scarmuega** [comment]
@rodolfofranco it's not possible to use this component directly from CRNA because Expo projects are not compatible with other native packages that require "linking". The only available option is to "Detach" the CRNA project and turn it into "regular" react-native project, but beware that this process is not reversible.

More info about the "Detach" process here:
https://docs.expo.io/versions/latest/guides/detach.html
